[package]
name = "subxt-eg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subxt = "0.33.0"
subxt-signer = "0.33.0"
tokio = { version = "1.33.0", features = ["rt-multi-thread"] }
